### ISSUE TITLE
AppwriteException: Invalid document structure: Unknown attribute: "email"

### ISSUE THREAD

**Issue by beginner154** [adrianhajdin/banking#74] opened 2024-10-26 14:00 UTC
On the moment where we test transfer from one card to another card I get this error in terminal:
AppwriteException: Invalid document structure: Unknown attribute: "email"
    at _Client.call (webpack-internal:///(rsc)/./node_modules/node-appwrite/dist/client.mjs:283:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Databases.createDocument (webpack-internal:///(rsc)/./node_modules/node-appwrite/dist/services/databases.mjs:1629:12)
    at async $$ACTION_0 (webpack-internal:///(rsc)/./lib/actions/transaction.actions.ts:25:32)
    at async C:\Users\user\Desktop\banking app (original)\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:39:418
    at async rw (C:\Users\user\Desktop\banking app (original)\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:38:7978)
    at async r6 (C:\Users\user\Desktop\banking app (original)\node_modules\next\dist\compiled\next-server\app-page.runtime.dev.js:41:1256)
    at async doRender (C:\Users\user\Desktop\banking app (original)\node_modules\next\dist\server\base-server.js:1438:30)
    at async cacheEntry.responseCache.get.routeKind (C:\Users\user\Desktop\banking app (original)\node_modules\next\dist\server\base-server.js:1599:28)

 code: 400,
  type: 'document_invalid_structure',
  response: {
    message: 'Invalid document structure: Unknown attribute: "email"',
    code: 400,
    type: 'document_invalid_structure',
    version: '1.6.0'
  }
}
Although i clearly checked appwrite for misspells and syntax errors
Nothing.

**Comment by mr-andrej** [comment] 2024-10-29 11:58
Hey @beginner154, this looks like a schema mismatch - Appwrite is saying it doesn't know about an email field in your collection but you're trying to save one.

The approach I used when I had an issue like this was to:
1. Open the Appwrite console and go to the collection's schema settings
2. Check if email exists in the collection schema
3. Add it if it's missing, or edit it if you have it but with a typo/some other small issue

Can you share the code where you're creating the document? It could help track this issue down faster.
A schema screenshot would be helpful too. Also, if you've already resolved your issue, don't forget to close this issue and share your solution.

Note: Common issues are usually case sensitivity (email vs Email), whitespace in field names or field type mismatches.

**Comment by StackTheCode** [comment] 2024-10-29 12:37
Hey @mr-andrej .Yeah it seems to be so but the funnniest part is i did not find any mismatches or i just simply didn't searched in right place.
1.My code
So here is the formSchema from PaymentTransferForm.tsx:
```
 const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      name: "",
      email: "",
      amount: "",
      senderBank: "",
      shareableId: "",
    },
  });
```
Transaction part where email validated properly:

```
 if (transfer) {
        const transaction = {
          name: data.name,
          amount: data.amount,
          senderId: senderBank.userId.$id,
          senderBankId: senderBank.$id,
          receiverId: receiverBank.userId.$id,
          receiverBankId: receiverBank.$id,
          email: data.email,
        };

```
        const newTransaction = await createTransaction(transaction);

 createTransaction from transactions.actions.ts:

```
export const createTransaction = async (transaction: CreateTransactionProps) => {
  try {
    const { database } = await createAdminClient();

    const newTransaction = await database.createDocument(
      DATABASE_ID!,
      TRANSACTION_COLLECTION_ID!,
      ID.unique(),
      {
        channel: 'online',
        category: 'Transfer',
        ...transaction
      }
    )

    return parseStringify(newTransaction);
  } catch (error) {
    console.log(error);
  }
}
```
2.Collection attributes:
users database where email is used only and it seems to me syntactically valid:

![users](https://github.com/user-attachments/assets/70e11c4b-9ebf-45ba-a3af-59d2e55db1e8)

In other collections we do not have email attributes

**Comment by mr-andrej** [comment] 2024-10-29 13:09
Thanks for the additional info, I think we're getting closer to the issue.

Looking at your schema screenshot and code, the problem is that you're trying to save an email field to your transaction collection, but that field isn't defined in the transaction collection's schema - it only exists in your users collection.

To fix this you have two options:
1. Either add an email attribute to your transaction collection's schema on Appwrite (recommended)
2. Or remove email from the transaction object (if you believe you don't need to persist it)

Your form and validation are okay! The error happens when Appwrite tries to save a field that isn't defined in that specific collection's schema.

To help illustrate what I mean a bit better: 

```
  if (transfer) {
        const transaction = {
          name: data.name,
          amount: data.amount,
          senderId: senderBank.userId.$id,
          senderBankId: senderBank.$id,
          receiverId: receiverBank.userId.$id,
          receiverBankId: receiverBank.$id,
          email: data.email, // <--- The email attribute that you're sending to Appwrite when you try to update the transaction collection
        };
```
        
When you call createTransaction it will try to create the new transaction document with all these attributes here. Since you mentioned that in other collections you do not have an email attribute, this is what is causing Appwrite to fail to save your transaction.      

Can you share what attributes are defined in your transactions collection?

**Comment by StackTheCode** [comment] 2024-10-29 13:34
@mr-andrej thank you very much for suggesting to create "email" attribute for transactions collection.Bug is fixed.I was thinking about doing this  but because in video i was following Adrian,and he did not create email field only:
   name
          amount
          senderId:
          senderBankId: 
          receiverId:
          receiverBankId: 
        Or maybe i did not pay enough attention.2nd issue i faced was alert "Attribute limit exceeded" because in video tutorial we were creating attributes with 2000 size ,then i adjusted every one of them to 200 and was finally able to create new attribute
So yeah 
SOLUTION:**ADD EMAIL FIELD TO COLLECTION IN APPWRITE DESPITE IT IS  NOT BEING SHOWED IN VDEO**

**Closed** 2024-10-29 13:35 UTC

**Comment by paragshende42** [comment] 2025-05-06 16:01
POST /app/interpretation 500 in 855ms
error making interpretation AppwriteException: Invalid document structure: Missing required attribute "term"
    at Generator.next (<anonymous>) {
  code: 400,
  type: 'document_invalid_structure',
  response: '{"message":"Invalid document structure: Missing required attribute \\"term\\"","code":400,"type":"document_invalid_structure","version":"1.6.2"}'
